### ISSUE TITLE
As a prospective user, I want to see screenshots of the app when I view the README, so I know how badass beautiful this thing is

### ISSUE THREAD

**Issue by mcw0933** [Xayrn/CardHunterUtils#20]
This issue is a placeholder so we can dump non-source screenshots and other supporting materials into Github, for linking to the readme.  Aren't we so clever.  :)

(No, we're not.  We shamelessly ripped this idea off.  http://solutionoptimist.com/2013/12/28/awesome-github-tricks/)

**Comment by mcw0933** [comment]
<img width="1552" alt="partyview" src="https://cloud.githubusercontent.com/assets/750196/9563854/c2cc30dc-4e60-11e5-9d32-f518419be975.png">
<img width="1552" alt="filters" src="https://cloud.githubusercontent.com/assets/750196/9564090/befbb808-4e68-11e5-9007-025a2b7eaf98.png">
<img width="1524" alt="itemcards" src="https://cloud.githubusercontent.com/assets/750196/9564091/befe4690-4e68-11e5-82f7-6b7e0ad53ffc.png">

**Comment by mcw0933** [comment]
<img width="1552" alt="allcards" src="https://cloud.githubusercontent.com/assets/750196/9564195/33ad3b74-4e6c-11e5-8929-a55e26a082d7.png">

**Comment by RyanHilbert** [comment]
Very cool. I see you've been doing some work on those backgrounds.

**Comment by mcw0933** [comment]
Yeah - just pushing some updates to the readme too.  I had a hack session with a friend last night and he suggested the README could use a bit more panache / user-friendliness.

I just noticed I still had a hard-coded `|| true` in `cardview.html` so it was always showing the comparisons.  Took that out, retaking this last shot so it's not showing dupes.

**Comment by mcw0933** [comment]
<img width="1552" alt="allcards" src="https://cloud.githubusercontent.com/assets/750196/9564246/73ca1a68-4e6e-11e5-8a74-cebc4eea3f8b.png">

**Comment by mcw0933** [comment]
<img width="1552" alt="allcards" src="https://cloud.githubusercontent.com/assets/750196/9569953/bb4246dc-4f49-11e5-8edc-c504c6f43147.png">

**Comment by mcw0933** [comment]
<img width="1524" alt="itemcards" src="https://cloud.githubusercontent.com/assets/750196/9569977/1a5b25d0-4f4a-11e5-887e-e0a3c93c0394.png">
